name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        working-directory: devtools/packages/workflow
        
      - name: Build workflow package
        run: bun run build
        working-directory: devtools/packages/workflow
        
      - name: Run tests
        run: bun run test
        working-directory: devtools/packages/workflow
        
      - name: Setup npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        
      - name: Publish to npm
        run: bun publish --access public
        working-directory: devtools/packages/workflow
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
