name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install root dependencies
        run: bun install
        working-directory: devtools
        
      - name: Build util package
        run: bun run build
        working-directory: devtools/packages/util
        
      - name: Build workflow package  
        run: bun run build
        working-directory: devtools/packages/workflow
        
      - name: Publish util to npm
        run: npm publish --access public
        working-directory: devtools/packages/util
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Publish workflow to npm
        run: npm publish --access public
        working-directory: devtools/packages/workflow
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
