name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm install --only=production
        working-directory: devtools/packages/workflow
        
      - name: Build package
        run: npm run build
        working-directory: devtools/packages/workflow
        
      - name: Run tests
        run: npm test
        working-directory: devtools/packages/workflow
        
      - name: Publish to npm
        run: npm publish --access public
        working-directory: devtools/packages/workflow
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
